name: Helm Chart CI

on:
  pull_request:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-chart-ci.yml'
      - '.github/scripts/*.sh'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-docs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Verify Docs updated
        run: .github/scripts/helm-docs.sh
